server: 
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shirotest
    username: root
    password: zg128328
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming: 
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jackson:
    serialization:
      indent-output: true
    
      